### ISSUE TITLE
Complete set of methods that interact upon the cache state / getIfPresent()

### ISSUE THREAD

**Issue by cruftex** [jsr107/jsr107spec#319]
Follow-up on #303:

The method putIfAbset() writes a value if it is not yet there. Consequently this would imply that the method getIfPresent() exits, but it doesn't.

I think getIfPresent() is the most important one (see comments / examples in #303), but there may be more "semantic holes" in the defined method set. E.g. putIfDifferent() could make sense also.

Further discussion: Don't we need the bulk variations, too: getIfPresentAll(), or putIfAbsentAll() or putIfDiffentAll()

**Comment by brianoliver** [comment]
Personally speaking (so others might disagree), I don't believe "complete consistency" is the goal of the JCache API or any API, Java or otherwise.   It's not a deliberate non-goal, but it's certainly not something we as a group strived to achieve.   If it was we'd have a combinatorial explosion of methods and corresponding semantics!

I think the motivation for "putIfAbsent" is to provide a common mechanism to support this commonly used operation (in almost all current implementations).   It was added before I joined the specification, but I'm pretty confident that is the reason.

For any/all other potentially missing methods, we've attempted to make sure EntryProcessors can to be used.  I think we strived to achieve a reasonable "balance".   I'm not saying we're missing things or didn't made mistakes, but I think adding the complete set of matching methods is slightly unrealistic and very much undesirable.

Remember, there are many companies that now implement this specification.   Adding/changing the specification requires an enormous amount of effort, not only from the maintenance leads, but also all of the individuals / companies as well.   There has to be a very strong reasons and support to change.

BTW: GetIfPresent is achievable using an EntryProcessor, simply because with in an EntryProcessor you can "ask" if the Entry is present and if so, return it.  If I understand this correctly, this is the semantic you're looking for.

**Comment by cruftex** [comment]
> I think the motivation for "putIfAbsent" is to provide a common mechanism to support this commonly used operation (in almost all current implementations).

This issue is mainly about getIfPresent(). Aren't there implementations around that implement something similar?

> I'm not saying we're missing things or didn't made mistakes, but I think adding the complete set of matching methods is slightly unrealistic and very much undesirable.

Whether it is desireable or undesireable, is a collaborative decision. If there is a majority of implementers that want to implement it, it is desireable. At least, if the standard wants to achieve to cover all things that (a mojority of) implementers find useful.

> Remember, there are many companies that now implement this specification. Adding/changing the specification requires an enormous amount of effort, not only from the maintenance leads, but also all of the individuals / companies as well. There has to be a very strong reasons and support to change.

JSR107 is gone. Adding a new method is (IMHO) an incompatible change. This means, this is a no issue to the maintenance leads.

Does JCache 2.0 need breaking changes to the Cache interface? If the answer is "unsure", what better can we do than collect all the minor and major deficiencies that we find?

Brain:
- can you label it with 2.0?
- can you comment on this just with an "implementor hat" on?

Maybe, I should have made clear upfront that I see this clearly as a 2.0 issue.

**Comment by brianoliver** [comment]
It's not so much what "implementors" want, it's what developer use-cases are and if "implementors" have been driven to support said use-cases.

For JCache, such specialized use-cases are typically implemented using EntryProcessors.   Where there's not a huge demand for a native method, like "getIfPresent", we make sure that EntryProcessors can be used in a manner to allow this.

I'll update the issue for 2.0.

**Comment by gregrluck** [comment]
No implementations out there have a getIfPresent method. get either returns the value or null if it is not present. There is a containsKey method which returns a boolean, true if present.

**Comment by cruftex** [comment]
I didn't checked it thoroughly, but: getIfPresent is present in Infinispan, Google Guava, Google Caffeine and cache2k (peek() which will be renamed) 

> get either returns the value or null if it is not present.

Yes, but invokes the loader, which is not the case for the getIfPresent() semantics and the reason why it is out there.

**Comment by gregrluck** [comment]
Jens agrees we cannot do anything on this in a maintenance release because it would break binary compatibility. 

Interesting that there are implementations out there that use this. Given that the key point is to have a look with no loading, for the record I think the method name peek is nice.
