### ISSUE TITLE
JMX statistics should be an optional feature

### ISSUE THREAD

**Issue by cruftex** [jsr107/jsr107spec#322]
A valid JCache implementation currently needs to implement statistics imposed via JMX, furthermore, the statistics updates are quite rigorously checked from the TCK.

1. A cache implementation can be useful without exposing JMX statistics (e.g. Guava)
2. A cache implementation could provide other means of statistics. The TCK implies that statistics are always updated instantly. But the statistic counters may lag, since the cache implementation may choose to optimize on locking and minimize the effects retrieving the statistics.

Making statistics optional could improve the adoption of the standard.

Change outline:

- Add JMX_STATISTICS to OptionalFeature
- Make JMX statistics test in TCK optional on CachingProvider.isSupported(JMX_STATISTICS)
- Add TCK test, that a 1.1 cache returns true to CachingProvider.isSupported(JMX_STATISTICS) if it supports JMX
- Change RI to return true CachingProvider.isSupported(JMX_STATISTICS)
- Add comment: Methods that enable/disable statistics, should ignore the request, if statistics support is not available with in the implementation
- The TCK needs to be validated, to correctly work, if JMX support is not available

Impact if introduced in 1.1:

- Applications using JMX, upgrading to  1.1 API and using an 1.0 implementation will still use JMX 
- Applications using the 1.1 API and a 1.0 implementation and checking for JMX support may falsely
- Implementations supporting 1.1 and JMX need to ensure that CachingProvider.isSupported(JMX_STATISTICS) == true

Adding the additional field to the OptionalFeature Enum is binary compatible.

The change seems feasible to me within a maintenance release.

I am a little in doubt whether there is enough backing for it. Why should representatives of existing implementations support something that they do not need? Hopefully there is: Making JCache easier to implement will lead to more people knowing and supporting the very core of the API.

**Comment by brianoliver** [comment]
> A valid JCache implementation currently needs to implement statistics imposed via JMX, furthermore,
> the statistics updates are quite rigorously checked from the TCK.

Correct.  The JCache Specification guarantees implementations will provide statistics via JMX as without them, it's next to impossible to track, tune or manage Caches!

However, the JCache Specification is very permissive as to when they are updated (although the TCK may be overly strict in this regard).

A possible solution here is;

a). To enhance the TCK so that there's no requirement for implementations to update statistics immediately (the specification deliberately makes no mention of when statistics are updated)

b). To enhance the specification to allow statistics to be turned on/off, through we probably wouldn't test this in the TCK.

> Making statistics optional could improve the adoption of the standard.

I don't think that's true.   Caches without statistics in an enterprise scenario don't seem to make much sense.   Improving the specification turn them off and relaxing the requirements in the TCK would seem to satisfy all of the main requirements above (eg: statistics may lag).

**Comment by brianoliver** [comment]
Raised TCK issue: https://github.com/jsr107/jsr107tck/issues/79 to relax JMX statistics.

Removing "turning off" JMX is unlikely to happen as any tooling vendor using existing JMX may break if the feature is removed.
