### ISSUE TITLE
Current StoreByValue/StoreByReference requirements are impractical

### ISSUE THREAD

**Issue by cruftex** [jsr107/jsr107spec#323]
What we have currently:

Configuration.isStoreByValue() == true as it is checked by the TCK means that key and value need to be always copied when it is moving in and out of the cache.

Configuration.isStoreByValue() == false as it is currently checked by the TCK means that the cache must store the value as reference, so a later mutation of the value must affect the cache state.

Configuration.isStoreByValue() == false, aka store by reference is defined as optional feature.

Configuration.isStoreByValue() == true, is the default.

Configuration.isStoreByValue() == true is addressed by 6 TCK tests.

Configuration.isStoreByValue() == false is addressed by 11 TCK tests.

Analysis:

1. Every cache must provide store by value semantics by default. This means a heap only cache needs to do copying when keys and values get in and out.

2. An normal application can never rely on store by reference semantics, since it is optional. Hence a normal application must request store by value semantics.

3. Although store by value is the default and this is a strong guarantee the TCK tests checking this behaviour are quite loose. What about: `Entry e = cache.iterator().next(); assertTrue(e.getValue() != e.getValue());` I have the strong feeling that I can come up with more, logically valid TCK tests that make all current implementations fail. Who wants to bet a beer on this?

4. Does the copying of keys mean that an application is allowed or should be encouraged to mutate the keys?

5. Is from a contract point of view the guarantee store by reference needed? No in the general case, since it is optional. And yes, since it is only the cache that can provide it if the application relies on it.

6. Is from a contract point of view the guarantee store by value needed? No, since the application can copy keys and values as needed itself.

7. Is it valid to say that store by value is only a safe guard for potentially erroneous applications? While this makes totally sense, giving the developer the guarantee to protect him from herself and request this in the API makes not.

8. How to implement a cache that is as efficient as possible (that is the reason why we do caching!) and that is caching entries in the heap and does overflow/passivation to a secondary storage if needed? This is useful, but it means that we have a mix of store by value and store by reference semantics. 

9. Does a normal application require store by value semantics or store by reference semantics? I think, as soon as an application explicitly relies on either of these semantics, it is a very special application. So, the option that an application does not require both of the additional guarantees that store by value or store by reference are giving is essentially missing.

**Comment by brianoliver** [comment]
I don't think any of content in this issue is actually an issue with the specification or TCK.   The content is  simply a series of questions for which you'd like answers.  Perhaps instead of raising them as issues, such questions could be asked on the mailing list?   

Some answers anyway ;)

> Every cache must provide store by value semantics by default. 

Correct.  JCache implementations are required to provide store-by-value semantics.   They may additionally (hence the term "optional") provide store-by-reference semantics for Cache Entries.

> This means a heap only cache needs to do copying when keys and values get in and out.

Correct, but only if the "heap-only-cache" provide wants to claim JCache compliance.   If a "heap-only-cache" implementation can't or won't "store-by-value" semantics, then by definition is not a JCache.   It can be some other non-compliant Cache that uses the JCache interfaces, but it can't ever claim to be JCache compliant as it can't satisfy the JCache specification requirements or semantics required by the TCK.

> An normal application can never rely on store by reference semantics, since it is optional. 
> Hence a normal application must request store by value semantics.

Correct.   Written another way, Applications are always guaranteed to at least have "store-by-value" semantics for any configured JCache provider.

Any application that requires "store-by-reference" semantics will naturally require a JCache implementation that provides "store-by-reference".

Applications that don't care about optional support of "store-by-reference", can always safely assume "store-by-value" (for compliant JCaches)

Applications that want to make intelligent dynamic decisions at runtime between "store-by-value" and "store-by-reference" based on their runtime configured providers are free to do so.

> Although store by value is the default and this is a strong guarantee the TCK tests checking this
> behavior are quite loose. 
> What about: Entry e = cache.iterator().next(); assertTrue(e.getValue() != e.getValue()); 
> I have the strong feeling that I can come up with more, logically valid TCK tests that make all current
> implementations fail. Who wants to bet a beer on this?

I'm sure we too can create an enormous number of logically valid TCK tests, most of which I think will ultimately serve little purpose.

If you strongly think these tests will be of value to the community, above and beyond the other investments we need to make, I'm certainly happy to listen.

> Does the copying of keys mean that an application is allowed or should be encouraged to mutate 
> the keys?

No.   But in a distributed environment, the copying of keys is unavoidable.

Ultimately the copying of keys / values will be revisited in Java 10 (due to Valhalla).

> Is from a contract point of view the guarantee store by reference needed? No in the general case, 
> since it is optional. And yes, since it is only the cache that can provide it if the application relies on it.

If an application requests a "store-by-reference", then an implementation absolutely needs to provide it (if it can).   If it can't we can throw an exception.  If an application wants to "test" the capability of an implementation, it easily can.

**Comment by cruftex** [comment]
Thanks for getting back to this!

> I don't think any of content in this issue is actually an issue with the specification or TCK. Some answers anyway ;)

The issue is, that most of the applications do not rely on store by value or store by reference semantics at all. So the either/or option is not useful.

To have store-by-value semantics is a valid choice of a cache implementation (or administrator that configures the application) to protect against "misbehaving" code. But is it really useful for an application to request store-by-value semantics from the cache? I am not sure, since it boils down to the question: Should it considered good practice for an applications to mutate key and value, after handing out the reference to the cache?

So, ultimately we encourage bad programming practice by providing this guarantee to the application.
OTOH it is not clearly defined what the guarantee really is.

Can somebody please comment with example applications that need store-by-value semantics?

My concrete proposal for JCache 2:

An application can select that it does not rely on store-by-value and store-by-reference semantics.

**Comment by brianoliver** [comment]
> The issue is, that most of the applications do not rely on store by value or store by reference semantics 
> at all. So the either/or option is not useful.

Completely disagree.   We deal with enterprise applications every single day that have to make this choice.   Some applications are happy to use "store-by-reference", especially when they know throughout the entire "surface" of code no part mutates information (and thus corrupts a cache).   Other applications must use "store-by-value" as a). they can't guarantee mutation of cache entries or b). they want to guarantee clean "copies".

To say that applications do not rely (or basically don't care) is erroneous.

Again, this is not an issue for the specification, but rather a question about the specification.   Such questions should be asked on the mailing list, not raise as issues to be fixed or repaired in the specification.   We'd do this "after" we know that we have to do something.

**Comment by brianoliver** [comment]
> My concrete proposal for JCache 2:
> An application can select that it does not rely on store-by-value and store-by-reference semantics.

I strongly reject this line of thinking.

It implies that developers could say "I don't care" and then, through no fault of their own, pass an entry to another layer in their application that does care, perhaps accidentally mutating an entry and corrupting the cache.

There are many more layers / tiers / libraries in an application than as single class that uses a JCache Cache.   While one part of a system "may not care", other parts may.   The suggestion opens the door to Cache corruption which little chance of diagnosing the problem.

**Comment by cruftex** [comment]
> There are many more layers / tiers / libraries in an application than as single class that uses a JCache Cache. While one part of a system "may not care", other parts may.

Yes. But ideally the problem, whether an object may be mutated or not, needs to be correctly addressed at the layer boundaries. The cache feature could be of some help here but is not the only solution to address this.

Right now the TCK does not check what happens when an object is mutated that is returned by the cache (correct me if I am wrong). This means a valid JCache store-by-value implementation, as enforced by the TCK now, may still have corrupted cache contents.

Formally, this is the guarantee:

````java
    long now = System.currentTimeMillis();
    cache.put(new Date(now), new Date(now));
    cache.get(new Date(now)).setTime(now + 1);
    assertEquals(new Date(now), cache.get(new Date(now)));
````

Either this needs to be added to the TCK or it should be documented that this may be implementation specific and the application cannot rely on it.

> The suggestion opens the door to Cache corruption which little chance of diagnosing the problem.

We are talking about the configuration within the code context. I see it as a way of the application to request specific semantics that it needs. In this case it means it is requesting no guarantees.

An application that only stores immutable objects, does not need any guarantees.

Some applications, where the code base is in good control, as you mention yourself, does not need any guarantees.

A caching vendor can always provide the store-by-value semantics when "i don't care semantics" are requested by the application code. I completely agree that in enterprise applications contexts it is desirable stick to the most robust functionality.

> Some applications are happy to use "store-by-reference", especially when they know throughout the entire "surface" of code no part mutates information (and thus corrupts a cache).

Exactly, this is the contradiction.

It makes no sense to request store-by-reference, when sure that no mutation happens. Store-by-reference is now designed to be an indicator for the cache that an application is doing mutation and relies on it. At least the TCK checks this semantics. The spec is a little vague and says "can potentially observe..." maybe this could be more explicit.

**Comment by cruftex** [comment]
I tested this:

````java
  @Test
  public void getAndMutate() {
    long now = System.currentTimeMillis();
    cache.put(new Date(now), new Date(now));
    cache.get(new Date(now)).setTime(now + 1);
    assertEquals(new Date(now), cache.get(new Date(now)));
  }

  @Test
  public void getTwice() {
    long now = System.currentTimeMillis();
    cache.put(new Date(now), new Date(now));
    Object o1 = cache.get(new Date(now));
    Object o2 = cache.get(new Date(now));
    assertTrue(o1 != o2);
  }

  @Test
  public void iteratorAccessValueTwice() {
    long now = System.currentTimeMillis();
    cache.put(new Date(now), new Date(now));
    Cache.Entry<Date, Date> e = cache.iterator().next();
    assertNotNull(e);
    assertTrue(e.getValue() != e.getValue());
  }
````

Result:

RI fails: iteratorAccessValueTwice(), rest passes
EHCache fails: iteratorAccessValueTwice(), rest passes
Hazelcast fails: iteratorAccessValueTwice(), rest passes
Apache Ignite fails: iteratorAccessValueTwice(), rest passes
Apache JCS fails: iteratorAccessValueTwice(), getAndMutate(), getTwice()

The versions can be looked up here: https://github.com/cruftex/jsr107-test-zoo

> I'm sure we too can create an enormous number of logically valid TCK tests, most of which I think will ultimately serve little purpose.

No, for your intended semantics a test like getAndMutate() is essentially missing.

**Comment by brianoliver** [comment]
Looking at these tests you're essentially saying we need to add tests (to TCK 1.1) that ensure when an implementation provides store-by-reference, that indeed, store-by-reference is actually being used.

**Comment by brianoliver** [comment]
> It makes no sense to request store-by-reference, when sure that no mutation happens. 

This is certainly not true.  Even when there are no mutations, store-by-reference is a perfectly valid (I'd say extremely useful and important) semantic.  It removes all requirements for "copying" values, which in a large system has a huge impact on performance, through-put and garbage collection.   Considering serialization (copying) objects is second only to network in terms of application impact, being able to eliminate copying is very important.

While to you it may not make sense, or in fact be a contradiction, it's extremely valuable.

> Store-by-reference is now designed to be an indicator for the cache that an application is doing 
> mutation and relies on it. 

No.  Store-by-reference is exactly that.   A requirement that a Cache stores only references to entries.   It's not an indicator that an application may mutate entries.

> At least the TCK checks this semantics. The spec is a little vague and says "can potentially observe..." 
> maybe this could be more explicit.

The TCK tests the semantics of the SPEC.  When the SPEC is a little vague, that is deliberate. In such circumstances tests will be "loose" or "non-existent", which is why we don't have "store-by-reference" tests.

**Comment by brianoliver** [comment]
Footnote:  Store-By-Reference will become very important when Project Valhalla is completed (hopefully for Java 10).

**Comment by cruftex** [comment]
> Looking at these tests you're essentially saying we need to add tests (to TCK 1.1) that ensure when an implementation provides store-by-reference, that indeed, store-by-reference is actually being used.

My tests show that there is actually already one JSR107 compliant cache implementation that does not protect against cache corruption when the store-by-value setting is used.

Either the TCK needs to be enforced and the Spec needs to be clarified on this, or the store-by-value setting gives no real guarantee to the developer.

**Comment by cruftex** [comment]
> This is certainly not true. Even when there are no mutations, store-by-reference is a perfectly valid (I'd say extremely useful and important) semantic. It removes all requirements for "copying" values, which in a large system has a huge impact on performance, through-put and garbage collection.

The store-by-reference setting not only removes the requirement to copy values, but it adds the requirement that every value is stored in the heap. It gives the guarantee that the application can exploit this fact and mutate the stored values.

There is the need to be able to store by reference, for the huge performance impact reasons you give above, but, OTOH not give the guarantee that everything is stored in the heap all the time.

A cache that stores some of the data in the heap and spills to disk or off heap, cannot guarantee store-by-reference semantics or store-by-value semantics, when it operates in the most efficient way and internally does store-by-reference as often as possible to get the best throughput.

If you just want the best throughput and do not mutate values, there is no need to request for the guarantees that store-by-value or store-by-reference give you.

**Comment by cruftex** [comment]
The underlying issue, which also leads to misunderstandings, is that store-by-reference and store-by-value are basic technical concepts which lead to certain semantics. The standard, however, cannot define the technical approach of the implementation, instead it can only define the semantics that a developer can expect.

With Java 10 in mind, it makes even more sense to get away from the technical concepts, but concentrate on the semantics. What about these three options:

#### ROBUST

The cache takes measures against cache corruption. This can be done either by serializing/deserializing, copying, or copying and write protecting the objects.
In case immutable objects are stored, the cache may return and use the references directly. 

An application may mutate its objects after an cache operation is completed.
("completion"  and async support needs more detail) 

An application may not mutate object references returned by the cache
(This requirement would be needed if the cache should be able to write protect objects)

#### PERFORMANCE

The cache can choose the most efficient strategy.

An application is not allowed to mutate objects after it handed the references to the cache, nor is an application allowed to mutate object references retrieved from the cache.

#### MUTATABLE VALUES

The cache stores the object references of the application.

The application is allowed to mutate value objects after it handed the reference to the cache.

The mutations need to become visible to all cache clients.

**Comment by brianoliver** [comment]
> The store-by-reference setting not only removes the requirement to copy values, but it adds the 
> requirement that every value is stored in the heap. It gives the guarantee that the application can 
> exploit this fact and mutate the stored values.

No it doesn't.  This is completely incorrect.  Furthermore it's demonstrably false to assume that "store-by-reference" means "values must be on the heap".  There are commercial products in existence (like those from Software AG/Terracotta), that historically allowed/provided "store-by-reference" semantics for Java objects/entries and yet no values were stored on the heap.  In fact, some were kept in a database, allowing Java Virtual Machines to be "shutdown" and "restarted", with references intact, shared across Java Virtual Machine boundaries!   (They achieved this through very clever runtime class instrumentation).

We know this because;

a). One of the co-spec leads was CTO at Terracotta.
b). We've talked / worked with Terracotta producing the specification.
c). We've used the product.
d). We've worked with customers that used the product.

Like the approach or not, it worked and provided the semantics you essentially say is mandated for "store-by-reference"... when it's not.

> There is the need to be able to store by reference, for the huge performance impact reasons you give 
> above, but, OTOH not give the guarantee that everything is stored in the heap all the time.

As I've mentioned previously, just because there is a need (or single use-case), does not justify adding new functionality to the JCache specification.  One or even two vendors implementing a Cache in a specific manner does not mean the feature(s) must be in the JCache standard, even as options.

In fact, we had to fight very hard to have the few options we currently have.   We know through personal experience, the Expert Group, the JCP, other JSR leads and the many Java Architects we've worked with on JCache that having too many options in a specification, especially ones that aren't easily implementable (or won't be implemented) degrades the value, applicability and usefulness of a specification.  Furthermore it makes it impossible to have a broad set of quality implementations.  If anything, we should have made the specification smaller, with less options, not larger with more options!

In retrospect we should have made "store-by-reference" mandatory and not optional, but that would mean certain products could never be JCache compliant in the simplest case.  Hence why only "store-by-value" is required.

eg: The JCache specification was never designed to be the the union of every Caching feature from every Caching product with those features which aren't implemented universally made into options!   

> A cache that stores some of the data in the heap and spills to disk or off heap, cannot guarantee 
> store-by-reference semantics or store-by-value semantics, when it operates in the most efficient way 
> and internally does store-by-reference as often as possible to get the best throughput.

(what you're talking about here is what's often called "near" caching)

And we know this!  But importantly, some vendors can do this, it's just that some can't.  eg: Hazelcast just added this type of functionality, yet others have had it for years.   Again, that's no reason for it to be in the specification.   In fact, while most vendors talk about "near" caching, almost all achieve it differently, with a wide degree of semantics.  Forcing all of the current vendors to adhere to a narrowly defined (so it's testable) specification in this space is not a workable solution.

The solution, as mentioned previously, is to provide your own configuration, just as all vendors seem to be able to do for semantics that fall outside of the specification.   Some implementations can be "compliant", some can't.

> If you just want the best throughput and do not mutate values, there is no need to request for the 
> guarantees that store-by-value or store-by-reference give you.

In which case, what you can do it provide your own configuration and implement it.  If it's JCache compliant great.   If it's not, it's not a JCache.   If it's "better" than JCache, then you can advertise it as such (but it's not a JCache).

In reality I think your questions/examples elude to what is commonly called "Cache Topologies".   This is something we very carefully voided discussing or introducing to the specification.   I know we have a very clear statement about this.

"Cache Topologies" vary from implementation to implementation, mostly due to design, architecture, performance and throughput considerations made by the vendors in their implementations.   Forcing "Cache Topologies" essentially "forces an implementation", obviously something that no vendor would agree with (and didn't).   Having a minimal semantic / topology like "store-by-value" is all that could be agreed.

**Comment by cruftex** [comment]
> No it doesn't. This is completely incorrect. Furthermore it's demonstrably false to assume that "store-by-reference" means "values must be on the heap". 

That is what the spec says in CacheConfiguration.isStoreByValue():

> .... Storage by reference only applies to the local heap  ....

Thanks for sharing more background, but excuse me when I do my best effort to interpret the words of the specification.

**Comment by cruftex** [comment]
> Forcing all of the current vendors to adhere to a narrowly defined (so it's testable) specification in this space is not a workable solution.

What I am requesting is exactly the opposite. Having a standard way, not to force a cache implementation to a semantic, that the application does not need.

**Comment by cruftex** [comment]
> As I've mentioned previously, just because there is a need (or single use-case), does not justify adding new functionality to the JCache specification.

I totally agree.

If the major use case of store-by-reference is performance and not mutability, why don't drop mutability?
