### ISSUE TITLE
CacheEntryEvent  getOldValue()

### ISSUE THREAD

**Issue by cruftex** [jsr107/jsr107spec#362]
The Spec says at `isOldValueAvailable()`

`Whether the old value is available.`

Should be precise about the fact, when the cache implementation sends an old value.
In case of a remove event this is not totally obvious.
#### TODO

The Spec needs to be updated at the following places:
- CacheEntryEvent.getOldValue()
- CacheEntryEvent.isOldValueAvailable()
- CacheEntryListenerConfiguration.isOldValueRequired()
- CacheEntryUpdatedListener

Enhancements to the TCK

Enhancements to the RI

**Comment by cruftex** [comment]
Thought it is an easy clarification, but it isn't. I'll just 

Sending on a remove the value as null and oldValue as the removed one, does not work with the TCK. So it is evident that the oldValue is not to be used for the remove event.

The TCK has no tests at all for `CacheEntryEvent.getOldValue()` and `CacheEntryEvent.isOldValueAvailable()`. 

The RI implementation thorws `UnsuppportedOperationException`, which is not in the Spec.

````
  @Override
  public V getOldValue() throws UnsupportedOperationException {
    if (isOldValueAvailable()) {
      return oldValue;
    } else {
      throw new UnsupportedOperationException("Old value is not available for key");
    }
  }
````

**Comment by cruftex** [comment]
Test with TCK git master.

Used EHCache coordinates:

````
            <properties>
                <!--################################################################################################################-->

                <!-- Implementation coordinates -->
                <implementation-groupId>org.ehcache</implementation-groupId>
                <implementation-artifactId>ehcache</implementation-artifactId>
                <implementation-version>3.0.1</implementation-version>

                <!-- CacheManager and Cache implementation. Used by the unwrap tests. -->
                <CacheManagerImpl>org.ehcache.CacheManager</CacheManagerImpl>
                <CacheImpl>org.ehcache.Cache</CacheImpl>
                <CacheEntryImpl>org.ehcache.Cache$Entry</CacheEntryImpl>

                <!--The MBeanServer, so that the TCK can resolve it. -->
                <javax.management.builder.initial>org.ehcache.jsr107.internal.tck.Eh107MBeanServerBuilder
                </javax.management.builder.initial>
                <org.jsr107.tck.management.agentId>anyvalue</org.jsr107.tck.management.agentId>

                <!--################################################################################################################-->


            </properties>

````

I am running the TCK with:

````
mvn -fn clean install
````

The `-fn` was added since two tests are failing, so the build continuous.

Result:

````
[INFO] Reactor Summary:
[INFO] 
[INFO] TCK Parent ......................................... SUCCESS [  1.468 s]
[INFO] App Domain ......................................... SUCCESS [  3.436 s]
[INFO] Test Domain ........................................ SUCCESS [  3.181 s]
[INFO] Cache Tests ........................................ SUCCESS [  6.177 s]
[INFO] Implementation Tester .............................. SUCCESS [  0.018 s]
[INFO] Implementation Tester - Specific Implementation .... FAILURE [ 34.007 s]
[INFO] CDI/Weld Annotations Test Harness .................. FAILURE [  0.045 s]
[INFO] Implementation Tester - CDI Annotations ............ FAILURE [  0.013 s]
[INFO] Spring Annotations Test Harness .................... FAILURE [  0.005 s]
[INFO] Implementation Tester - Spring Annotations ......... FAILURE [  0.006 s]
[INFO] Guice Annotations Test Harness ..................... FAILURE [  0.004 s]
[INFO] Implementation Tester - Guice Annotations .......... FAILURE [  0.007 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 48.583 s
[INFO] Finished at: 2016-06-16T10:15:23+02:00
[INFO] Final Memory: 49M/548M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.9:test (default-test) on project specific-implementation-tester: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/jeans/ideaWork/jsr107-maintenance/jsr107tck/implementation-tester/specific-implementation-tester/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] Failed to execute goal on project cdi-weld-annotations-test-harness: Could not resolve dependencies for project javax.cache:cdi-weld-annotations-test-harness:jar:1.1.0-SNAPSHOT: Failure to find org.jsr107.ri:cache-annotations-ri-cdi:jar:3.0.1 in http://repository.jboss.org/nexus/content/groups/public-jboss/ was cached in the local repository, resolution will not be reattempted until the update interval of jboss.maven.repo has elapsed or updates are forced -> [Help 2]
[ERROR] Failed to execute goal on project cdi-annotations-tester: Could not resolve dependencies for project javax.cache:cdi-annotations-tester:jar:1.1.0-SNAPSHOT: Failure to find org.jsr107.ri:cache-annotations-ri-cdi:jar:3.0.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 2]
[ERROR] Failed to execute goal on project spring-annotations-test-harness: Could not resolve dependencies for project javax.cache:spring-annotations-test-harness:jar:1.1.0-SNAPSHOT: Failure to find org.jsr107.ri:cache-annotations-ri-spring:jar:3.0.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 2]
[ERROR] Failed to execute goal on project spring-annotations-tester: Could not resolve dependencies for project javax.cache:spring-annotations-tester:jar:1.1.0-SNAPSHOT: Failure to find org.jsr107.ri:cache-annotations-ri-spring:jar:3.0.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 2]
[ERROR] Failed to execute goal on project guice-annotations-test-harness: Could not resolve dependencies for project javax.cache:guice-annotations-test-harness:jar:1.1.0-SNAPSHOT: Failure to find org.jsr107.ri:cache-annotations-ri-guice:jar:3.0.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 2]
[ERROR] Failed to execute goal on project guice-annotations-tester: Could not resolve dependencies for project javax.cache:guice-annotations-tester:jar:1.1.0-SNAPSHOT: Failure to find org.jsr107.ri:cache-annotations-ri-guice:jar:3.0.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :specific-implementation-tester
[INFO] Build failures were ignored.
````

The hopping point is:

````
[ERROR] Failed to execute goal on project cdi-weld-annotations-test-harness: Could not resolve dependencies for project javax.cache:cdi-weld-annotations-test-harness:jar:1.1.0-SNAPSHOT: Failure to find org.jsr107.ri:cache-annotations-ri-cdi:jar:3.0.1
````

**Comment by cruftex** [comment]
Here is the full log of the build.

[build-log.txt](https://github.com/jsr107/jsr107spec/files/317963/build-log.txt)

**Comment by gregrluck** [comment]
Whether the old value is available is set in the CacheEntryListenerConfiguration interface. 

/**
   * Determines if the old value should be provided to the
   * {@link CacheEntryListener}.
   *
   * @return <code>true</code> if the old value is required by the
   *         {@link CacheEntryListener}
   */
  boolean isOldValueRequired();

There is a MutableCacheEntryListenerConfiguration class which allows it to be passed in. A user defined CacheEntryListener is allowed to implement as many of the sub-interfaces as it wants. 

The usual thing is that the old value is always known to remove, expire and update, but not to created. However the spec does not say instead making it user selectable at time of creating the MutableCacheEntryListenerConfiguration. 

Because a user can set this to true for any type of listener an implementation must be able to supply the old value if required. Of course the value will always be null for create. 

Added a test to check that the old value is returned when set to true. 

The RI always sets the old value for update.

//created
dispatcher.addEvent(CacheEntryCreatedListener.class, new RICacheEntryEvent<K, V>(this, key, value, EventType.CREATED));

//updated
dispatcher.addEvent(CacheEntryUpdatedListener.class,
            new RICacheEntryEvent<K, V>(this, key, value, oldValue,
                EventType.UPDATED));

//expired
dispatcher.addEvent(CacheEntryExpiredListener.class,
        new RICacheEntryEvent<K, V>(this, key, expiredValue, EXPIRED));


//removed
dispatcher.addEvent(CacheEntryRemovedListener.class,
            new RICacheEntryEvent<K, V>(this, key, value, REMOVED));

Updated CacheEntryEvent to implement getValue from Cache.Entry so that behaviour can be specified and added JavaDoc as follows:

/**
   * Returns the value stored in the cache when this entry was created.
   * <p>
   * The value will be available
   * for {@link CacheEntryCreatedListener}, {@link CacheEntryExpiredListener}
   * and {@link CacheEntryRemovedListener}
   * if {@link CacheEntryListenerConfiguration#isOldValueRequired()} is true.
   *
   * @return the value corresponding to this entry
   */
  public abstract V getValue();

  /**
   * Returns the previous value, that existed prior to the
   * modification of the Entry value. The old value will be available
   * for {@link CacheEntryUpdatedListener}
   * if {@link CacheEntryListenerConfiguration#isOldValueRequired()} is true.
   *
   * @return the previous value or <code>null</code> if there was no previous value
   */
  public abstract V getOldValue();

  /**
   * Whether the old value is available. The old value will be available
   * for {@link CacheEntryUpdatedListener} 
   * if {@link CacheEntryListenerConfiguration#isOldValueRequired()} is true. 
   *
   * @return true if the old value is populated
   */
  public abstract boolean isOldValueAvailable();
